# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy

builds:
  - id: scanner
    binary: rok-scanner
    main: ./cmd/rok-scanner
    tags:
      - static
    goos:
      - linux
    goarch:
      - amd64
  - id: server
    binary: rok-server
    main: ./cmd/rok-server
    tags:
      - static
    goos:
      - linux
    goarch:
      - amd64
  - id: remote
    binary: rok-remote
    main: ./cmd/rok-remote
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

nfpms:
  - id: remotepackage
    package_name: rokmonster-remote
    file_name_template: "rokmonster-remote_{{ .Os }}_{{ .Arch }}"
    vendor: Julius Lisauskas
    maintainer: Julius Lisauskas <julius@lisauskas.lt>
    builds:
      - remote
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    overrides:
      deb:
        dependencies:
          - adb
      rpm:
        dependencies:
          - android-tools
  - id: ocr-package
    package_name: rokmonster-ocr
    file_name_template: "rokmonster-ocr_{{ .Os }}_{{ .Arch }}"
    vendor: Julius Lisauskas
    maintainer: Julius Lisauskas <julius@lisauskas.lt>
    builds:
      - server
      - scanner
    formats:
      - deb
    bindir: /usr/bin
    overrides:
      deb:
        dependencies:
          - libtesseract4
  
dockers:
  - ids:
    - ocr-package
 
    image_templates:
    - "ghcr.io/rokmonster/ocr:{{ .Tag }}"
    - "ghcr.io/rokmonster/ocr:latest"

    dockerfile: 'Dockerfile.debian'
    use: docker

    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--platform=linux/amd64"

archives:
  - id: rokmonster-ocr
    name_template: "rokmonster-ocr_{{ .Os }}_{{ .Arch }}"
    builds:
      - server
      - scanner
    format: tar.gz
    files:
    - src: license*
    - src: LICENSE*
    - src: readme*
    - src: README*
    - src: changelog*
    - src: CHANGELOG*   
    - media/*.png
    - templates/*.json
  - id: rokmonster-remote
    name_template: "rokmonster-remote_{{ .Os }}_{{ .Arch }}"
    builds:
      - remote
    format: tar.gz

announce:
  discord:
    enabled: true
    message_template: 'ROK Monster OCR {{.Tag}} is out! Check it out at {{ .ReleaseURL }}'
    
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
